/* eslint-disable */
import * as types from './graphql';
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "\n  mutation login($email: String!, $password: String!, $rememberMe: Boolean) {\n    login(username: $email, password: $password, rememberMe: $rememberMe) {\n      __typename\n      ... on CurrentUser {\n        id\n        identifier\n      }\n      ... on ErrorResult {\n        errorCode\n        message\n      }\n    }\n  }\n": typeof types.LoginDocument,
    "\n  mutation logout {\n    logout {\n      success\n    }\n  }\n": typeof types.LogoutDocument,
    "\n  mutation registerCustomerAccount($input: RegisterCustomerInput!) {\n    registerCustomerAccount(input: $input) {\n      __typename\n      ... on Success {\n        success\n      }\n      ... on ErrorResult {\n        errorCode\n        message\n      }\n    }\n  }\n": typeof types.RegisterCustomerAccountDocument,
    "\n  mutation verifyCustomerAccount($token: String!, $password: String) {\n    verifyCustomerAccount(token: $token, password: $password) {\n      __typename\n      ... on CurrentUser {\n        id\n        identifier\n      }\n      ... on ErrorResult {\n        errorCode\n        message\n      }\n    }\n  }\n": typeof types.VerifyCustomerAccountDocument,
    "\n  mutation updateCustomer($input: UpdateCustomerInput!) {\n    updateCustomer(input: $input) {\n      __typename\n    }\n  }\n": typeof types.UpdateCustomerDocument,
    "\n  mutation requestUpdateCustomerEmailAddress(\n    $password: String!\n    $newEmailAddress: String!\n  ) {\n    requestUpdateCustomerEmailAddress(\n      password: $password\n      newEmailAddress: $newEmailAddress\n    ) {\n      __typename\n      ... on ErrorResult {\n        errorCode\n        message\n      }\n    }\n  }\n": typeof types.RequestUpdateCustomerEmailAddressDocument,
    "\n  mutation updateCustomerEmailAddress($token: String!) {\n    updateCustomerEmailAddress(token: $token) {\n      __typename\n      ... on ErrorResult {\n        errorCode\n        message\n      }\n    }\n  }\n": typeof types.UpdateCustomerEmailAddressDocument,
    "\n  mutation updateCustomerAddress($input: UpdateAddressInput!) {\n    updateCustomerAddress(input: $input) {\n      __typename\n    }\n  }\n": typeof types.UpdateCustomerAddressDocument,
    "\n  mutation createCustomerAddress($input: CreateAddressInput!) {\n    createCustomerAddress(input: $input) {\n      __typename\n    }\n  }\n": typeof types.CreateCustomerAddressDocument,
    "\n  mutation deleteCustomerAddress($id: ID!) {\n    deleteCustomerAddress(id: $id) {\n      success\n    }\n  }\n": typeof types.DeleteCustomerAddressDocument,
    "\n  mutation updateCustomerPassword(\n    $currentPassword: String!\n    $newPassword: String!\n  ) {\n    updateCustomerPassword(\n      currentPassword: $currentPassword\n      newPassword: $newPassword\n    ) {\n      __typename\n      ... on Success {\n        success\n      }\n      ... on ErrorResult {\n        errorCode\n        message\n      }\n    }\n  }\n": typeof types.UpdateCustomerPasswordDocument,
    "\n  mutation requestPasswordReset($emailAddress: String!) {\n    requestPasswordReset(emailAddress: $emailAddress) {\n      __typename\n      ... on Success {\n        success\n      }\n      ... on ErrorResult {\n        errorCode\n        message\n      }\n    }\n  }\n": typeof types.RequestPasswordResetDocument,
    "\n  mutation resetPassword($token: String!, $password: String!) {\n    resetPassword(token: $token, password: $password) {\n      __typename\n      ... on CurrentUser {\n        id\n        identifier\n      }\n      ... on ErrorResult {\n        errorCode\n        message\n      }\n    }\n  }\n": typeof types.ResetPasswordDocument,
    "\n  query activeChannel {\n    activeChannel {\n      id\n      currencyCode\n    }\n  }\n": typeof types.ActiveChannelDocument,
    "\n  query eligibleShippingMethods {\n    eligibleShippingMethods {\n      id\n      name\n      description\n      metadata\n      price\n      priceWithTax\n    }\n  }\n": typeof types.EligibleShippingMethodsDocument,
    "\n  query eligiblePaymentMethods {\n    eligiblePaymentMethods {\n      id\n      code\n      name\n      description\n      eligibilityMessage\n      isEligible\n    }\n  }\n": typeof types.EligiblePaymentMethodsDocument,
    "\n  query nextOrderStates {\n    nextOrderStates\n  }\n": typeof types.NextOrderStatesDocument,
    "\n  query availableCountries {\n    availableCountries {\n      id\n      name\n      code\n    }\n  }\n": typeof types.AvailableCountriesDocument,
    "\n  mutation addPaymentToOrder($input: PaymentInput!) {\n    addPaymentToOrder(input: $input) {\n      ...OrderDetail\n      ... on ErrorResult {\n        errorCode\n        message\n      }\n    }\n  }\n": typeof types.AddPaymentToOrderDocument,
    "\n  mutation transitionOrderToState($state: String!) {\n    transitionOrderToState(state: $state) {\n      ...OrderDetail\n      ... on ErrorResult {\n        errorCode\n        message\n      }\n    }\n  }\n": typeof types.TransitionOrderToStateDocument,
    "\n  mutation generateRazorpayOrderId($vendureOrderId: ID!) {\n    generateRazorpayOrderId(orderId: $vendureOrderId) {\n      __typename\n      ... on RazorpayOrderIdSuccess {\n        razorpayOrderId\n      }\n      ... on RazorpayOrderIdGenerationError {\n        errorCode\n        message\n      }\n    }\n  }\n": typeof types.GenerateRazorpayOrderIdDocument,
    "\n  query collections($options: CollectionListOptions) {\n    collections(options: $options) {\n      items {\n        id\n        name\n        slug\n        parent {\n          name\n        }\n        featuredAsset {\n          id\n          preview\n        }\n      }\n    }\n  }\n": typeof types.CollectionsDocument,
    "\n  query collection($slug: String, $id: ID) {\n    collection(slug: $slug, id: $id) {\n      id\n      name\n      slug\n      featuredAsset {\n        id\n        preview\n      }\n      assets {\n        id\n        preview\n      }\n      breadcrumbs {\n        id\n        name\n        slug\n      }\n      children {\n        id\n        name\n        slug\n        featuredAsset {\n          id\n          preview\n        }\n      }\n    }\n  }\n": typeof types.CollectionDocument,
    "\n  query activeCustomer {\n    activeCustomer {\n      id\n      firstName\n      lastName\n    }\n  }\n": typeof types.ActiveCustomerDocument,
    "\n  query activeCustomerDetails {\n    activeCustomer {\n      id\n      title\n      firstName\n      lastName\n      phoneNumber\n      emailAddress\n    }\n  }\n": typeof types.ActiveCustomerDetailsDocument,
    "\n  query activeCustomerAddresses {\n    activeCustomer {\n      id\n      addresses {\n        id\n        company\n        fullName\n        streetLine1\n        streetLine2\n        city\n        province\n        postalCode\n        country {\n          id\n          code\n          name\n        }\n        phoneNumber\n        defaultShippingAddress\n        defaultBillingAddress\n      }\n    }\n  }\n": typeof types.ActiveCustomerAddressesDocument,
    "\n  query activeCustomerOrderList($orderListOptions: OrderListOptions) {\n    activeCustomer {\n      orders(options: $orderListOptions) {\n        totalItems\n        items {\n          code\n          state\n          orderPlacedAt\n          currencyCode\n          totalWithTax\n          fulfillments {\n            trackingCode\n          }\n          lines {\n            quantity\n            featuredAsset {\n              preview\n            }\n            productVariant {\n              name\n            }\n          }\n        }\n      }\n    }\n  }\n": typeof types.ActiveCustomerOrderListDocument,
    "\n  query activeCustomerOrderDetails($orderCode: String!) {\n    activeCustomer {\n      orders(options: { filter: { code: { eq: $orderCode } } }) {\n        items {\n          code\n          state\n          orderPlacedAt\n          currencyCode\n          subTotal\n          subTotalWithTax\n          total\n          totalWithTax\n          shippingWithTax\n          shippingLines {\n            priceWithTax\n          }\n          taxSummary {\n            taxBase\n            taxTotal\n          }\n          discounts {\n            amountWithTax\n          }\n          fulfillments {\n            trackingCode\n          }\n          lines {\n            quantity\n            discountedLinePriceWithTax\n            discountedUnitPriceWithTax\n            fulfillmentLines {\n              quantity\n              fulfillment {\n                state\n                updatedAt\n              }\n            }\n            featuredAsset {\n              name\n              source\n              preview\n            }\n            productVariant {\n              name\n              sku\n              currencyCode\n              priceWithTax\n              product {\n                slug\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n": typeof types.ActiveCustomerOrderDetailsDocument,
    "\n  query getCollectionBySlug($slug: String!) {\n    collection(slug: $slug) {\n      id\n      name\n      slug\n      description\n      customFields {\n        customData\n      }\n      featuredAsset {\n        id\n        preview\n      }\n      assets {\n        id\n        preview\n      }\n      breadcrumbs {\n        id\n        name\n        slug\n      }\n      children {\n        id\n        name\n        slug\n      }\n      parent {\n        id\n        name\n        slug\n      }\n      createdAt\n      updatedAt\n      position\n      languageCode\n      translations {\n        id\n        languageCode\n        name\n        description\n        slug\n      }\n    }\n  }\n": typeof types.getCollectionBySlugDocument,
    "\n  mutation applyCouponCode($couponCode: String!) {\n    applyCouponCode(couponCode: $couponCode) {\n      ... on Order {\n        ...OrderDetail\n      }\n      ... on CouponCodeExpiredError {\n        errorCode\n        message\n        couponCode\n      }\n      ... on CouponCodeInvalidError {\n        errorCode\n        message\n        couponCode\n      }\n      ... on CouponCodeLimitError {\n        errorCode\n        message\n        couponCode\n        limit\n      }\n    }\n  }\n": typeof types.ApplyCouponCodeDocument,
    "\n  mutation setCustomerForOrder($input: CreateCustomerInput!) {\n    setCustomerForOrder(input: $input) {\n      ...OrderDetail\n      ... on ErrorResult {\n        errorCode\n        message\n      }\n    }\n  }\n": typeof types.SetCustomerForOrderDocument,
    "\n  mutation setOrderShippingAddress($input: CreateAddressInput!) {\n    setOrderShippingAddress(input: $input) {\n      ...OrderDetail\n      ... on ErrorResult {\n        errorCode\n        message\n      }\n    }\n  }\n": typeof types.SetOrderShippingAddressDocument,
    "\n  mutation setOrderShippingMethod($shippingMethodId: [ID!]!) {\n    setOrderShippingMethod(shippingMethodId: $shippingMethodId) {\n      ...OrderDetail\n      ... on ErrorResult {\n        errorCode\n        message\n      }\n    }\n  }\n": typeof types.SetOrderShippingMethodDocument,
    "\n  mutation setOrderCustomFields($input: UpdateOrderInput!) {\n    setOrderCustomFields(input: $input) {\n      ...OrderDetail\n      ... on ErrorResult {\n        errorCode\n        message\n      }\n    }\n  }\n": typeof types.SetOrderCustomFieldsDocument,
    "\n  mutation addItemToOrder($productVariantId: ID!, $quantity: Int!) {\n    addItemToOrder(productVariantId: $productVariantId, quantity: $quantity) {\n      ...OrderDetail\n      ... on ErrorResult {\n        errorCode\n        message\n      }\n    }\n  }\n": typeof types.AddItemToOrderDocument,
    "\n  mutation removeOrderLine($orderLineId: ID!) {\n    removeOrderLine(orderLineId: $orderLineId) {\n      ...OrderDetail\n      ... on ErrorResult {\n        errorCode\n        message\n      }\n    }\n  }\n": typeof types.RemoveOrderLineDocument,
    "\n  mutation adjustOrderLine($orderLineId: ID!, $quantity: Int!) {\n    adjustOrderLine(orderLineId: $orderLineId, quantity: $quantity) {\n      ...OrderDetail\n      ... on ErrorResult {\n        errorCode\n        message\n      }\n    }\n  }\n": typeof types.AdjustOrderLineDocument,
    "\n  fragment OrderDetail on Order {\n    __typename\n    id\n    code\n    active\n    createdAt\n    state\n    currencyCode\n    totalQuantity\n    subTotal\n    subTotalWithTax\n    taxSummary {\n      description\n      taxRate\n      taxTotal\n    }\n    shippingWithTax\n    totalWithTax\n    customer {\n      id\n      firstName\n      lastName\n      emailAddress\n      customFields {\n        icaiRegistrationNumber\n        gstin\n      }\n    }\n    shippingAddress {\n      fullName\n      streetLine1\n      streetLine2\n      company\n      city\n      province\n      postalCode\n      countryCode\n      phoneNumber\n    }\n    shippingLines {\n      shippingMethod {\n        id\n        name\n      }\n      priceWithTax\n    }\n    lines {\n      id\n      unitPriceWithTax\n      linePriceWithTax\n      quantity\n      featuredAsset {\n        id\n        preview\n      }\n      productVariant {\n        id\n        name\n        price\n        product {\n          id\n          name\n          slug\n        }\n      }\n    }\n    payments {\n      id\n      state\n      method\n      amount\n      metadata\n      transactionId\n      customFields {\n        easebuzzToken\n      }\n    }\n    couponCodes\n    customFields {\n      attemptMonth\n      attemptYear\n      examLevel\n      additionalInformation\n    }\n  }\n": typeof types.OrderDetailFragmentDoc,
    "\n  query activeOrder {\n    activeOrder {\n      ...OrderDetail\n    }\n  }\n": typeof types.ActiveOrderDocument,
    "\n  query orderByCode($code: String!) {\n    orderByCode(code: $code) {\n      ...OrderDetail\n    }\n  }\n": typeof types.OrderByCodeDocument,
    "\n  query activeShippingMethods {\n    activeShippingMethods {\n      id\n      name\n      description\n      code\n    }\n  }\n": typeof types.ActiveShippingMethodsDocument,
    "\n  fragment DetailedProduct on Product {\n    id\n    name\n    description\n    customFields {\n      language\n      additionalFeatures\n      ByFaculty\n    }\n    collections {\n      id\n      slug\n      name\n      breadcrumbs {\n        id\n        name\n        slug\n      }\n    }\n    facetValues {\n      facet {\n        id\n        code\n        name\n      }\n      id\n      code\n      name\n    }\n    featuredAsset {\n      id\n      preview\n    }\n    assets {\n      id\n      preview\n    }\n    optionGroups {\n      id\n      name\n      code\n      options {\n        id\n        name\n      }\n    }\n    variants {\n      id\n      name\n      priceWithTax\n      currencyCode\n      sku\n      stockLevel\n      options {\n        id\n        name\n        group {\n          id\n          name\n        }\n      }\n      featuredAsset {\n        id\n        preview\n      }\n    }\n  }\n": typeof types.DetailedProductFragmentDoc,
    "\n  query product($slug: String, $id: ID) {\n    product(slug: $slug, id: $id) {\n      ...DetailedProduct\n    }\n  }\n": typeof types.ProductDocument,
    "\n  fragment ListedProduct on SearchResult {\n    productId\n    productName\n    slug\n    productAsset {\n      id\n      preview\n    }\n    currencyCode\n    priceWithTax {\n      ... on PriceRange {\n        min\n        max\n      }\n      ... on SinglePrice {\n        value\n      }\n    }\n  }\n": typeof types.ListedProductFragmentDoc,
    "\n  query search($input: SearchInput!) {\n    search(input: $input) {\n      totalItems\n      items {\n        ...ListedProduct\n      }\n      facetValues {\n        count\n        facetValue {\n          id\n          name\n          facet {\n            id\n            name\n          }\n        }\n      }\n    }\n  }\n  \n": typeof types.SearchDocument,
    "\n  query searchFacetValues($input: SearchInput!) {\n    search(input: $input) {\n      totalItems\n      facetValues {\n        count\n        facetValue {\n          id\n          name\n          facet {\n            id\n            name\n          }\n        }\n      }\n    }\n  }\n  \n": typeof types.SearchFacetValuesDocument,
};
const documents: Documents = {
    "\n  mutation login($email: String!, $password: String!, $rememberMe: Boolean) {\n    login(username: $email, password: $password, rememberMe: $rememberMe) {\n      __typename\n      ... on CurrentUser {\n        id\n        identifier\n      }\n      ... on ErrorResult {\n        errorCode\n        message\n      }\n    }\n  }\n": types.LoginDocument,
    "\n  mutation logout {\n    logout {\n      success\n    }\n  }\n": types.LogoutDocument,
    "\n  mutation registerCustomerAccount($input: RegisterCustomerInput!) {\n    registerCustomerAccount(input: $input) {\n      __typename\n      ... on Success {\n        success\n      }\n      ... on ErrorResult {\n        errorCode\n        message\n      }\n    }\n  }\n": types.RegisterCustomerAccountDocument,
    "\n  mutation verifyCustomerAccount($token: String!, $password: String) {\n    verifyCustomerAccount(token: $token, password: $password) {\n      __typename\n      ... on CurrentUser {\n        id\n        identifier\n      }\n      ... on ErrorResult {\n        errorCode\n        message\n      }\n    }\n  }\n": types.VerifyCustomerAccountDocument,
    "\n  mutation updateCustomer($input: UpdateCustomerInput!) {\n    updateCustomer(input: $input) {\n      __typename\n    }\n  }\n": types.UpdateCustomerDocument,
    "\n  mutation requestUpdateCustomerEmailAddress(\n    $password: String!\n    $newEmailAddress: String!\n  ) {\n    requestUpdateCustomerEmailAddress(\n      password: $password\n      newEmailAddress: $newEmailAddress\n    ) {\n      __typename\n      ... on ErrorResult {\n        errorCode\n        message\n      }\n    }\n  }\n": types.RequestUpdateCustomerEmailAddressDocument,
    "\n  mutation updateCustomerEmailAddress($token: String!) {\n    updateCustomerEmailAddress(token: $token) {\n      __typename\n      ... on ErrorResult {\n        errorCode\n        message\n      }\n    }\n  }\n": types.UpdateCustomerEmailAddressDocument,
    "\n  mutation updateCustomerAddress($input: UpdateAddressInput!) {\n    updateCustomerAddress(input: $input) {\n      __typename\n    }\n  }\n": types.UpdateCustomerAddressDocument,
    "\n  mutation createCustomerAddress($input: CreateAddressInput!) {\n    createCustomerAddress(input: $input) {\n      __typename\n    }\n  }\n": types.CreateCustomerAddressDocument,
    "\n  mutation deleteCustomerAddress($id: ID!) {\n    deleteCustomerAddress(id: $id) {\n      success\n    }\n  }\n": types.DeleteCustomerAddressDocument,
    "\n  mutation updateCustomerPassword(\n    $currentPassword: String!\n    $newPassword: String!\n  ) {\n    updateCustomerPassword(\n      currentPassword: $currentPassword\n      newPassword: $newPassword\n    ) {\n      __typename\n      ... on Success {\n        success\n      }\n      ... on ErrorResult {\n        errorCode\n        message\n      }\n    }\n  }\n": types.UpdateCustomerPasswordDocument,
    "\n  mutation requestPasswordReset($emailAddress: String!) {\n    requestPasswordReset(emailAddress: $emailAddress) {\n      __typename\n      ... on Success {\n        success\n      }\n      ... on ErrorResult {\n        errorCode\n        message\n      }\n    }\n  }\n": types.RequestPasswordResetDocument,
    "\n  mutation resetPassword($token: String!, $password: String!) {\n    resetPassword(token: $token, password: $password) {\n      __typename\n      ... on CurrentUser {\n        id\n        identifier\n      }\n      ... on ErrorResult {\n        errorCode\n        message\n      }\n    }\n  }\n": types.ResetPasswordDocument,
    "\n  query activeChannel {\n    activeChannel {\n      id\n      currencyCode\n    }\n  }\n": types.ActiveChannelDocument,
    "\n  query eligibleShippingMethods {\n    eligibleShippingMethods {\n      id\n      name\n      description\n      metadata\n      price\n      priceWithTax\n    }\n  }\n": types.EligibleShippingMethodsDocument,
    "\n  query eligiblePaymentMethods {\n    eligiblePaymentMethods {\n      id\n      code\n      name\n      description\n      eligibilityMessage\n      isEligible\n    }\n  }\n": types.EligiblePaymentMethodsDocument,
    "\n  query nextOrderStates {\n    nextOrderStates\n  }\n": types.NextOrderStatesDocument,
    "\n  query availableCountries {\n    availableCountries {\n      id\n      name\n      code\n    }\n  }\n": types.AvailableCountriesDocument,
    "\n  mutation addPaymentToOrder($input: PaymentInput!) {\n    addPaymentToOrder(input: $input) {\n      ...OrderDetail\n      ... on ErrorResult {\n        errorCode\n        message\n      }\n    }\n  }\n": types.AddPaymentToOrderDocument,
    "\n  mutation transitionOrderToState($state: String!) {\n    transitionOrderToState(state: $state) {\n      ...OrderDetail\n      ... on ErrorResult {\n        errorCode\n        message\n      }\n    }\n  }\n": types.TransitionOrderToStateDocument,
    "\n  mutation generateRazorpayOrderId($vendureOrderId: ID!) {\n    generateRazorpayOrderId(orderId: $vendureOrderId) {\n      __typename\n      ... on RazorpayOrderIdSuccess {\n        razorpayOrderId\n      }\n      ... on RazorpayOrderIdGenerationError {\n        errorCode\n        message\n      }\n    }\n  }\n": types.GenerateRazorpayOrderIdDocument,
    "\n  query collections($options: CollectionListOptions) {\n    collections(options: $options) {\n      items {\n        id\n        name\n        slug\n        parent {\n          name\n        }\n        featuredAsset {\n          id\n          preview\n        }\n      }\n    }\n  }\n": types.CollectionsDocument,
    "\n  query collection($slug: String, $id: ID) {\n    collection(slug: $slug, id: $id) {\n      id\n      name\n      slug\n      featuredAsset {\n        id\n        preview\n      }\n      assets {\n        id\n        preview\n      }\n      breadcrumbs {\n        id\n        name\n        slug\n      }\n      children {\n        id\n        name\n        slug\n        featuredAsset {\n          id\n          preview\n        }\n      }\n    }\n  }\n": types.CollectionDocument,
    "\n  query activeCustomer {\n    activeCustomer {\n      id\n      firstName\n      lastName\n    }\n  }\n": types.ActiveCustomerDocument,
    "\n  query activeCustomerDetails {\n    activeCustomer {\n      id\n      title\n      firstName\n      lastName\n      phoneNumber\n      emailAddress\n    }\n  }\n": types.ActiveCustomerDetailsDocument,
    "\n  query activeCustomerAddresses {\n    activeCustomer {\n      id\n      addresses {\n        id\n        company\n        fullName\n        streetLine1\n        streetLine2\n        city\n        province\n        postalCode\n        country {\n          id\n          code\n          name\n        }\n        phoneNumber\n        defaultShippingAddress\n        defaultBillingAddress\n      }\n    }\n  }\n": types.ActiveCustomerAddressesDocument,
    "\n  query activeCustomerOrderList($orderListOptions: OrderListOptions) {\n    activeCustomer {\n      orders(options: $orderListOptions) {\n        totalItems\n        items {\n          code\n          state\n          orderPlacedAt\n          currencyCode\n          totalWithTax\n          fulfillments {\n            trackingCode\n          }\n          lines {\n            quantity\n            featuredAsset {\n              preview\n            }\n            productVariant {\n              name\n            }\n          }\n        }\n      }\n    }\n  }\n": types.ActiveCustomerOrderListDocument,
    "\n  query activeCustomerOrderDetails($orderCode: String!) {\n    activeCustomer {\n      orders(options: { filter: { code: { eq: $orderCode } } }) {\n        items {\n          code\n          state\n          orderPlacedAt\n          currencyCode\n          subTotal\n          subTotalWithTax\n          total\n          totalWithTax\n          shippingWithTax\n          shippingLines {\n            priceWithTax\n          }\n          taxSummary {\n            taxBase\n            taxTotal\n          }\n          discounts {\n            amountWithTax\n          }\n          fulfillments {\n            trackingCode\n          }\n          lines {\n            quantity\n            discountedLinePriceWithTax\n            discountedUnitPriceWithTax\n            fulfillmentLines {\n              quantity\n              fulfillment {\n                state\n                updatedAt\n              }\n            }\n            featuredAsset {\n              name\n              source\n              preview\n            }\n            productVariant {\n              name\n              sku\n              currencyCode\n              priceWithTax\n              product {\n                slug\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n": types.ActiveCustomerOrderDetailsDocument,
    "\n  query getCollectionBySlug($slug: String!) {\n    collection(slug: $slug) {\n      id\n      name\n      slug\n      description\n      customFields {\n        customData\n      }\n      featuredAsset {\n        id\n        preview\n      }\n      assets {\n        id\n        preview\n      }\n      breadcrumbs {\n        id\n        name\n        slug\n      }\n      children {\n        id\n        name\n        slug\n      }\n      parent {\n        id\n        name\n        slug\n      }\n      createdAt\n      updatedAt\n      position\n      languageCode\n      translations {\n        id\n        languageCode\n        name\n        description\n        slug\n      }\n    }\n  }\n": types.getCollectionBySlugDocument,
    "\n  mutation applyCouponCode($couponCode: String!) {\n    applyCouponCode(couponCode: $couponCode) {\n      ... on Order {\n        ...OrderDetail\n      }\n      ... on CouponCodeExpiredError {\n        errorCode\n        message\n        couponCode\n      }\n      ... on CouponCodeInvalidError {\n        errorCode\n        message\n        couponCode\n      }\n      ... on CouponCodeLimitError {\n        errorCode\n        message\n        couponCode\n        limit\n      }\n    }\n  }\n": types.ApplyCouponCodeDocument,
    "\n  mutation setCustomerForOrder($input: CreateCustomerInput!) {\n    setCustomerForOrder(input: $input) {\n      ...OrderDetail\n      ... on ErrorResult {\n        errorCode\n        message\n      }\n    }\n  }\n": types.SetCustomerForOrderDocument,
    "\n  mutation setOrderShippingAddress($input: CreateAddressInput!) {\n    setOrderShippingAddress(input: $input) {\n      ...OrderDetail\n      ... on ErrorResult {\n        errorCode\n        message\n      }\n    }\n  }\n": types.SetOrderShippingAddressDocument,
    "\n  mutation setOrderShippingMethod($shippingMethodId: [ID!]!) {\n    setOrderShippingMethod(shippingMethodId: $shippingMethodId) {\n      ...OrderDetail\n      ... on ErrorResult {\n        errorCode\n        message\n      }\n    }\n  }\n": types.SetOrderShippingMethodDocument,
    "\n  mutation setOrderCustomFields($input: UpdateOrderInput!) {\n    setOrderCustomFields(input: $input) {\n      ...OrderDetail\n      ... on ErrorResult {\n        errorCode\n        message\n      }\n    }\n  }\n": types.SetOrderCustomFieldsDocument,
    "\n  mutation addItemToOrder($productVariantId: ID!, $quantity: Int!) {\n    addItemToOrder(productVariantId: $productVariantId, quantity: $quantity) {\n      ...OrderDetail\n      ... on ErrorResult {\n        errorCode\n        message\n      }\n    }\n  }\n": types.AddItemToOrderDocument,
    "\n  mutation removeOrderLine($orderLineId: ID!) {\n    removeOrderLine(orderLineId: $orderLineId) {\n      ...OrderDetail\n      ... on ErrorResult {\n        errorCode\n        message\n      }\n    }\n  }\n": types.RemoveOrderLineDocument,
    "\n  mutation adjustOrderLine($orderLineId: ID!, $quantity: Int!) {\n    adjustOrderLine(orderLineId: $orderLineId, quantity: $quantity) {\n      ...OrderDetail\n      ... on ErrorResult {\n        errorCode\n        message\n      }\n    }\n  }\n": types.AdjustOrderLineDocument,
    "\n  fragment OrderDetail on Order {\n    __typename\n    id\n    code\n    active\n    createdAt\n    state\n    currencyCode\n    totalQuantity\n    subTotal\n    subTotalWithTax\n    taxSummary {\n      description\n      taxRate\n      taxTotal\n    }\n    shippingWithTax\n    totalWithTax\n    customer {\n      id\n      firstName\n      lastName\n      emailAddress\n      customFields {\n        icaiRegistrationNumber\n        gstin\n      }\n    }\n    shippingAddress {\n      fullName\n      streetLine1\n      streetLine2\n      company\n      city\n      province\n      postalCode\n      countryCode\n      phoneNumber\n    }\n    shippingLines {\n      shippingMethod {\n        id\n        name\n      }\n      priceWithTax\n    }\n    lines {\n      id\n      unitPriceWithTax\n      linePriceWithTax\n      quantity\n      featuredAsset {\n        id\n        preview\n      }\n      productVariant {\n        id\n        name\n        price\n        product {\n          id\n          name\n          slug\n        }\n      }\n    }\n    payments {\n      id\n      state\n      method\n      amount\n      metadata\n      transactionId\n      customFields {\n        easebuzzToken\n      }\n    }\n    couponCodes\n    customFields {\n      attemptMonth\n      attemptYear\n      examLevel\n      additionalInformation\n    }\n  }\n": types.OrderDetailFragmentDoc,
    "\n  query activeOrder {\n    activeOrder {\n      ...OrderDetail\n    }\n  }\n": types.ActiveOrderDocument,
    "\n  query orderByCode($code: String!) {\n    orderByCode(code: $code) {\n      ...OrderDetail\n    }\n  }\n": types.OrderByCodeDocument,
    "\n  query activeShippingMethods {\n    activeShippingMethods {\n      id\n      name\n      description\n      code\n    }\n  }\n": types.ActiveShippingMethodsDocument,
    "\n  fragment DetailedProduct on Product {\n    id\n    name\n    description\n    customFields {\n      language\n      additionalFeatures\n      ByFaculty\n    }\n    collections {\n      id\n      slug\n      name\n      breadcrumbs {\n        id\n        name\n        slug\n      }\n    }\n    facetValues {\n      facet {\n        id\n        code\n        name\n      }\n      id\n      code\n      name\n    }\n    featuredAsset {\n      id\n      preview\n    }\n    assets {\n      id\n      preview\n    }\n    optionGroups {\n      id\n      name\n      code\n      options {\n        id\n        name\n      }\n    }\n    variants {\n      id\n      name\n      priceWithTax\n      currencyCode\n      sku\n      stockLevel\n      options {\n        id\n        name\n        group {\n          id\n          name\n        }\n      }\n      featuredAsset {\n        id\n        preview\n      }\n    }\n  }\n": types.DetailedProductFragmentDoc,
    "\n  query product($slug: String, $id: ID) {\n    product(slug: $slug, id: $id) {\n      ...DetailedProduct\n    }\n  }\n": types.ProductDocument,
    "\n  fragment ListedProduct on SearchResult {\n    productId\n    productName\n    slug\n    productAsset {\n      id\n      preview\n    }\n    currencyCode\n    priceWithTax {\n      ... on PriceRange {\n        min\n        max\n      }\n      ... on SinglePrice {\n        value\n      }\n    }\n  }\n": types.ListedProductFragmentDoc,
    "\n  query search($input: SearchInput!) {\n    search(input: $input) {\n      totalItems\n      items {\n        ...ListedProduct\n      }\n      facetValues {\n        count\n        facetValue {\n          id\n          name\n          facet {\n            id\n            name\n          }\n        }\n      }\n    }\n  }\n  \n": types.SearchDocument,
    "\n  query searchFacetValues($input: SearchInput!) {\n    search(input: $input) {\n      totalItems\n      facetValues {\n        count\n        facetValue {\n          id\n          name\n          facet {\n            id\n            name\n          }\n        }\n      }\n    }\n  }\n  \n": types.SearchFacetValuesDocument,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = graphql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function graphql(source: string): unknown;

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation login($email: String!, $password: String!, $rememberMe: Boolean) {\n    login(username: $email, password: $password, rememberMe: $rememberMe) {\n      __typename\n      ... on CurrentUser {\n        id\n        identifier\n      }\n      ... on ErrorResult {\n        errorCode\n        message\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation login($email: String!, $password: String!, $rememberMe: Boolean) {\n    login(username: $email, password: $password, rememberMe: $rememberMe) {\n      __typename\n      ... on CurrentUser {\n        id\n        identifier\n      }\n      ... on ErrorResult {\n        errorCode\n        message\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation logout {\n    logout {\n      success\n    }\n  }\n"): (typeof documents)["\n  mutation logout {\n    logout {\n      success\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation registerCustomerAccount($input: RegisterCustomerInput!) {\n    registerCustomerAccount(input: $input) {\n      __typename\n      ... on Success {\n        success\n      }\n      ... on ErrorResult {\n        errorCode\n        message\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation registerCustomerAccount($input: RegisterCustomerInput!) {\n    registerCustomerAccount(input: $input) {\n      __typename\n      ... on Success {\n        success\n      }\n      ... on ErrorResult {\n        errorCode\n        message\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation verifyCustomerAccount($token: String!, $password: String) {\n    verifyCustomerAccount(token: $token, password: $password) {\n      __typename\n      ... on CurrentUser {\n        id\n        identifier\n      }\n      ... on ErrorResult {\n        errorCode\n        message\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation verifyCustomerAccount($token: String!, $password: String) {\n    verifyCustomerAccount(token: $token, password: $password) {\n      __typename\n      ... on CurrentUser {\n        id\n        identifier\n      }\n      ... on ErrorResult {\n        errorCode\n        message\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation updateCustomer($input: UpdateCustomerInput!) {\n    updateCustomer(input: $input) {\n      __typename\n    }\n  }\n"): (typeof documents)["\n  mutation updateCustomer($input: UpdateCustomerInput!) {\n    updateCustomer(input: $input) {\n      __typename\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation requestUpdateCustomerEmailAddress(\n    $password: String!\n    $newEmailAddress: String!\n  ) {\n    requestUpdateCustomerEmailAddress(\n      password: $password\n      newEmailAddress: $newEmailAddress\n    ) {\n      __typename\n      ... on ErrorResult {\n        errorCode\n        message\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation requestUpdateCustomerEmailAddress(\n    $password: String!\n    $newEmailAddress: String!\n  ) {\n    requestUpdateCustomerEmailAddress(\n      password: $password\n      newEmailAddress: $newEmailAddress\n    ) {\n      __typename\n      ... on ErrorResult {\n        errorCode\n        message\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation updateCustomerEmailAddress($token: String!) {\n    updateCustomerEmailAddress(token: $token) {\n      __typename\n      ... on ErrorResult {\n        errorCode\n        message\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation updateCustomerEmailAddress($token: String!) {\n    updateCustomerEmailAddress(token: $token) {\n      __typename\n      ... on ErrorResult {\n        errorCode\n        message\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation updateCustomerAddress($input: UpdateAddressInput!) {\n    updateCustomerAddress(input: $input) {\n      __typename\n    }\n  }\n"): (typeof documents)["\n  mutation updateCustomerAddress($input: UpdateAddressInput!) {\n    updateCustomerAddress(input: $input) {\n      __typename\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation createCustomerAddress($input: CreateAddressInput!) {\n    createCustomerAddress(input: $input) {\n      __typename\n    }\n  }\n"): (typeof documents)["\n  mutation createCustomerAddress($input: CreateAddressInput!) {\n    createCustomerAddress(input: $input) {\n      __typename\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation deleteCustomerAddress($id: ID!) {\n    deleteCustomerAddress(id: $id) {\n      success\n    }\n  }\n"): (typeof documents)["\n  mutation deleteCustomerAddress($id: ID!) {\n    deleteCustomerAddress(id: $id) {\n      success\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation updateCustomerPassword(\n    $currentPassword: String!\n    $newPassword: String!\n  ) {\n    updateCustomerPassword(\n      currentPassword: $currentPassword\n      newPassword: $newPassword\n    ) {\n      __typename\n      ... on Success {\n        success\n      }\n      ... on ErrorResult {\n        errorCode\n        message\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation updateCustomerPassword(\n    $currentPassword: String!\n    $newPassword: String!\n  ) {\n    updateCustomerPassword(\n      currentPassword: $currentPassword\n      newPassword: $newPassword\n    ) {\n      __typename\n      ... on Success {\n        success\n      }\n      ... on ErrorResult {\n        errorCode\n        message\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation requestPasswordReset($emailAddress: String!) {\n    requestPasswordReset(emailAddress: $emailAddress) {\n      __typename\n      ... on Success {\n        success\n      }\n      ... on ErrorResult {\n        errorCode\n        message\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation requestPasswordReset($emailAddress: String!) {\n    requestPasswordReset(emailAddress: $emailAddress) {\n      __typename\n      ... on Success {\n        success\n      }\n      ... on ErrorResult {\n        errorCode\n        message\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation resetPassword($token: String!, $password: String!) {\n    resetPassword(token: $token, password: $password) {\n      __typename\n      ... on CurrentUser {\n        id\n        identifier\n      }\n      ... on ErrorResult {\n        errorCode\n        message\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation resetPassword($token: String!, $password: String!) {\n    resetPassword(token: $token, password: $password) {\n      __typename\n      ... on CurrentUser {\n        id\n        identifier\n      }\n      ... on ErrorResult {\n        errorCode\n        message\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query activeChannel {\n    activeChannel {\n      id\n      currencyCode\n    }\n  }\n"): (typeof documents)["\n  query activeChannel {\n    activeChannel {\n      id\n      currencyCode\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query eligibleShippingMethods {\n    eligibleShippingMethods {\n      id\n      name\n      description\n      metadata\n      price\n      priceWithTax\n    }\n  }\n"): (typeof documents)["\n  query eligibleShippingMethods {\n    eligibleShippingMethods {\n      id\n      name\n      description\n      metadata\n      price\n      priceWithTax\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query eligiblePaymentMethods {\n    eligiblePaymentMethods {\n      id\n      code\n      name\n      description\n      eligibilityMessage\n      isEligible\n    }\n  }\n"): (typeof documents)["\n  query eligiblePaymentMethods {\n    eligiblePaymentMethods {\n      id\n      code\n      name\n      description\n      eligibilityMessage\n      isEligible\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query nextOrderStates {\n    nextOrderStates\n  }\n"): (typeof documents)["\n  query nextOrderStates {\n    nextOrderStates\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query availableCountries {\n    availableCountries {\n      id\n      name\n      code\n    }\n  }\n"): (typeof documents)["\n  query availableCountries {\n    availableCountries {\n      id\n      name\n      code\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation addPaymentToOrder($input: PaymentInput!) {\n    addPaymentToOrder(input: $input) {\n      ...OrderDetail\n      ... on ErrorResult {\n        errorCode\n        message\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation addPaymentToOrder($input: PaymentInput!) {\n    addPaymentToOrder(input: $input) {\n      ...OrderDetail\n      ... on ErrorResult {\n        errorCode\n        message\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation transitionOrderToState($state: String!) {\n    transitionOrderToState(state: $state) {\n      ...OrderDetail\n      ... on ErrorResult {\n        errorCode\n        message\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation transitionOrderToState($state: String!) {\n    transitionOrderToState(state: $state) {\n      ...OrderDetail\n      ... on ErrorResult {\n        errorCode\n        message\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation generateRazorpayOrderId($vendureOrderId: ID!) {\n    generateRazorpayOrderId(orderId: $vendureOrderId) {\n      __typename\n      ... on RazorpayOrderIdSuccess {\n        razorpayOrderId\n      }\n      ... on RazorpayOrderIdGenerationError {\n        errorCode\n        message\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation generateRazorpayOrderId($vendureOrderId: ID!) {\n    generateRazorpayOrderId(orderId: $vendureOrderId) {\n      __typename\n      ... on RazorpayOrderIdSuccess {\n        razorpayOrderId\n      }\n      ... on RazorpayOrderIdGenerationError {\n        errorCode\n        message\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query collections($options: CollectionListOptions) {\n    collections(options: $options) {\n      items {\n        id\n        name\n        slug\n        parent {\n          name\n        }\n        featuredAsset {\n          id\n          preview\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query collections($options: CollectionListOptions) {\n    collections(options: $options) {\n      items {\n        id\n        name\n        slug\n        parent {\n          name\n        }\n        featuredAsset {\n          id\n          preview\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query collection($slug: String, $id: ID) {\n    collection(slug: $slug, id: $id) {\n      id\n      name\n      slug\n      featuredAsset {\n        id\n        preview\n      }\n      assets {\n        id\n        preview\n      }\n      breadcrumbs {\n        id\n        name\n        slug\n      }\n      children {\n        id\n        name\n        slug\n        featuredAsset {\n          id\n          preview\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query collection($slug: String, $id: ID) {\n    collection(slug: $slug, id: $id) {\n      id\n      name\n      slug\n      featuredAsset {\n        id\n        preview\n      }\n      assets {\n        id\n        preview\n      }\n      breadcrumbs {\n        id\n        name\n        slug\n      }\n      children {\n        id\n        name\n        slug\n        featuredAsset {\n          id\n          preview\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query activeCustomer {\n    activeCustomer {\n      id\n      firstName\n      lastName\n    }\n  }\n"): (typeof documents)["\n  query activeCustomer {\n    activeCustomer {\n      id\n      firstName\n      lastName\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query activeCustomerDetails {\n    activeCustomer {\n      id\n      title\n      firstName\n      lastName\n      phoneNumber\n      emailAddress\n    }\n  }\n"): (typeof documents)["\n  query activeCustomerDetails {\n    activeCustomer {\n      id\n      title\n      firstName\n      lastName\n      phoneNumber\n      emailAddress\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query activeCustomerAddresses {\n    activeCustomer {\n      id\n      addresses {\n        id\n        company\n        fullName\n        streetLine1\n        streetLine2\n        city\n        province\n        postalCode\n        country {\n          id\n          code\n          name\n        }\n        phoneNumber\n        defaultShippingAddress\n        defaultBillingAddress\n      }\n    }\n  }\n"): (typeof documents)["\n  query activeCustomerAddresses {\n    activeCustomer {\n      id\n      addresses {\n        id\n        company\n        fullName\n        streetLine1\n        streetLine2\n        city\n        province\n        postalCode\n        country {\n          id\n          code\n          name\n        }\n        phoneNumber\n        defaultShippingAddress\n        defaultBillingAddress\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query activeCustomerOrderList($orderListOptions: OrderListOptions) {\n    activeCustomer {\n      orders(options: $orderListOptions) {\n        totalItems\n        items {\n          code\n          state\n          orderPlacedAt\n          currencyCode\n          totalWithTax\n          fulfillments {\n            trackingCode\n          }\n          lines {\n            quantity\n            featuredAsset {\n              preview\n            }\n            productVariant {\n              name\n            }\n          }\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query activeCustomerOrderList($orderListOptions: OrderListOptions) {\n    activeCustomer {\n      orders(options: $orderListOptions) {\n        totalItems\n        items {\n          code\n          state\n          orderPlacedAt\n          currencyCode\n          totalWithTax\n          fulfillments {\n            trackingCode\n          }\n          lines {\n            quantity\n            featuredAsset {\n              preview\n            }\n            productVariant {\n              name\n            }\n          }\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query activeCustomerOrderDetails($orderCode: String!) {\n    activeCustomer {\n      orders(options: { filter: { code: { eq: $orderCode } } }) {\n        items {\n          code\n          state\n          orderPlacedAt\n          currencyCode\n          subTotal\n          subTotalWithTax\n          total\n          totalWithTax\n          shippingWithTax\n          shippingLines {\n            priceWithTax\n          }\n          taxSummary {\n            taxBase\n            taxTotal\n          }\n          discounts {\n            amountWithTax\n          }\n          fulfillments {\n            trackingCode\n          }\n          lines {\n            quantity\n            discountedLinePriceWithTax\n            discountedUnitPriceWithTax\n            fulfillmentLines {\n              quantity\n              fulfillment {\n                state\n                updatedAt\n              }\n            }\n            featuredAsset {\n              name\n              source\n              preview\n            }\n            productVariant {\n              name\n              sku\n              currencyCode\n              priceWithTax\n              product {\n                slug\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query activeCustomerOrderDetails($orderCode: String!) {\n    activeCustomer {\n      orders(options: { filter: { code: { eq: $orderCode } } }) {\n        items {\n          code\n          state\n          orderPlacedAt\n          currencyCode\n          subTotal\n          subTotalWithTax\n          total\n          totalWithTax\n          shippingWithTax\n          shippingLines {\n            priceWithTax\n          }\n          taxSummary {\n            taxBase\n            taxTotal\n          }\n          discounts {\n            amountWithTax\n          }\n          fulfillments {\n            trackingCode\n          }\n          lines {\n            quantity\n            discountedLinePriceWithTax\n            discountedUnitPriceWithTax\n            fulfillmentLines {\n              quantity\n              fulfillment {\n                state\n                updatedAt\n              }\n            }\n            featuredAsset {\n              name\n              source\n              preview\n            }\n            productVariant {\n              name\n              sku\n              currencyCode\n              priceWithTax\n              product {\n                slug\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query getCollectionBySlug($slug: String!) {\n    collection(slug: $slug) {\n      id\n      name\n      slug\n      description\n      customFields {\n        customData\n      }\n      featuredAsset {\n        id\n        preview\n      }\n      assets {\n        id\n        preview\n      }\n      breadcrumbs {\n        id\n        name\n        slug\n      }\n      children {\n        id\n        name\n        slug\n      }\n      parent {\n        id\n        name\n        slug\n      }\n      createdAt\n      updatedAt\n      position\n      languageCode\n      translations {\n        id\n        languageCode\n        name\n        description\n        slug\n      }\n    }\n  }\n"): (typeof documents)["\n  query getCollectionBySlug($slug: String!) {\n    collection(slug: $slug) {\n      id\n      name\n      slug\n      description\n      customFields {\n        customData\n      }\n      featuredAsset {\n        id\n        preview\n      }\n      assets {\n        id\n        preview\n      }\n      breadcrumbs {\n        id\n        name\n        slug\n      }\n      children {\n        id\n        name\n        slug\n      }\n      parent {\n        id\n        name\n        slug\n      }\n      createdAt\n      updatedAt\n      position\n      languageCode\n      translations {\n        id\n        languageCode\n        name\n        description\n        slug\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation applyCouponCode($couponCode: String!) {\n    applyCouponCode(couponCode: $couponCode) {\n      ... on Order {\n        ...OrderDetail\n      }\n      ... on CouponCodeExpiredError {\n        errorCode\n        message\n        couponCode\n      }\n      ... on CouponCodeInvalidError {\n        errorCode\n        message\n        couponCode\n      }\n      ... on CouponCodeLimitError {\n        errorCode\n        message\n        couponCode\n        limit\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation applyCouponCode($couponCode: String!) {\n    applyCouponCode(couponCode: $couponCode) {\n      ... on Order {\n        ...OrderDetail\n      }\n      ... on CouponCodeExpiredError {\n        errorCode\n        message\n        couponCode\n      }\n      ... on CouponCodeInvalidError {\n        errorCode\n        message\n        couponCode\n      }\n      ... on CouponCodeLimitError {\n        errorCode\n        message\n        couponCode\n        limit\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation setCustomerForOrder($input: CreateCustomerInput!) {\n    setCustomerForOrder(input: $input) {\n      ...OrderDetail\n      ... on ErrorResult {\n        errorCode\n        message\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation setCustomerForOrder($input: CreateCustomerInput!) {\n    setCustomerForOrder(input: $input) {\n      ...OrderDetail\n      ... on ErrorResult {\n        errorCode\n        message\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation setOrderShippingAddress($input: CreateAddressInput!) {\n    setOrderShippingAddress(input: $input) {\n      ...OrderDetail\n      ... on ErrorResult {\n        errorCode\n        message\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation setOrderShippingAddress($input: CreateAddressInput!) {\n    setOrderShippingAddress(input: $input) {\n      ...OrderDetail\n      ... on ErrorResult {\n        errorCode\n        message\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation setOrderShippingMethod($shippingMethodId: [ID!]!) {\n    setOrderShippingMethod(shippingMethodId: $shippingMethodId) {\n      ...OrderDetail\n      ... on ErrorResult {\n        errorCode\n        message\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation setOrderShippingMethod($shippingMethodId: [ID!]!) {\n    setOrderShippingMethod(shippingMethodId: $shippingMethodId) {\n      ...OrderDetail\n      ... on ErrorResult {\n        errorCode\n        message\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation setOrderCustomFields($input: UpdateOrderInput!) {\n    setOrderCustomFields(input: $input) {\n      ...OrderDetail\n      ... on ErrorResult {\n        errorCode\n        message\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation setOrderCustomFields($input: UpdateOrderInput!) {\n    setOrderCustomFields(input: $input) {\n      ...OrderDetail\n      ... on ErrorResult {\n        errorCode\n        message\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation addItemToOrder($productVariantId: ID!, $quantity: Int!) {\n    addItemToOrder(productVariantId: $productVariantId, quantity: $quantity) {\n      ...OrderDetail\n      ... on ErrorResult {\n        errorCode\n        message\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation addItemToOrder($productVariantId: ID!, $quantity: Int!) {\n    addItemToOrder(productVariantId: $productVariantId, quantity: $quantity) {\n      ...OrderDetail\n      ... on ErrorResult {\n        errorCode\n        message\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation removeOrderLine($orderLineId: ID!) {\n    removeOrderLine(orderLineId: $orderLineId) {\n      ...OrderDetail\n      ... on ErrorResult {\n        errorCode\n        message\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation removeOrderLine($orderLineId: ID!) {\n    removeOrderLine(orderLineId: $orderLineId) {\n      ...OrderDetail\n      ... on ErrorResult {\n        errorCode\n        message\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation adjustOrderLine($orderLineId: ID!, $quantity: Int!) {\n    adjustOrderLine(orderLineId: $orderLineId, quantity: $quantity) {\n      ...OrderDetail\n      ... on ErrorResult {\n        errorCode\n        message\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation adjustOrderLine($orderLineId: ID!, $quantity: Int!) {\n    adjustOrderLine(orderLineId: $orderLineId, quantity: $quantity) {\n      ...OrderDetail\n      ... on ErrorResult {\n        errorCode\n        message\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  fragment OrderDetail on Order {\n    __typename\n    id\n    code\n    active\n    createdAt\n    state\n    currencyCode\n    totalQuantity\n    subTotal\n    subTotalWithTax\n    taxSummary {\n      description\n      taxRate\n      taxTotal\n    }\n    shippingWithTax\n    totalWithTax\n    customer {\n      id\n      firstName\n      lastName\n      emailAddress\n      customFields {\n        icaiRegistrationNumber\n        gstin\n      }\n    }\n    shippingAddress {\n      fullName\n      streetLine1\n      streetLine2\n      company\n      city\n      province\n      postalCode\n      countryCode\n      phoneNumber\n    }\n    shippingLines {\n      shippingMethod {\n        id\n        name\n      }\n      priceWithTax\n    }\n    lines {\n      id\n      unitPriceWithTax\n      linePriceWithTax\n      quantity\n      featuredAsset {\n        id\n        preview\n      }\n      productVariant {\n        id\n        name\n        price\n        product {\n          id\n          name\n          slug\n        }\n      }\n    }\n    payments {\n      id\n      state\n      method\n      amount\n      metadata\n      transactionId\n      customFields {\n        easebuzzToken\n      }\n    }\n    couponCodes\n    customFields {\n      attemptMonth\n      attemptYear\n      examLevel\n      additionalInformation\n    }\n  }\n"): (typeof documents)["\n  fragment OrderDetail on Order {\n    __typename\n    id\n    code\n    active\n    createdAt\n    state\n    currencyCode\n    totalQuantity\n    subTotal\n    subTotalWithTax\n    taxSummary {\n      description\n      taxRate\n      taxTotal\n    }\n    shippingWithTax\n    totalWithTax\n    customer {\n      id\n      firstName\n      lastName\n      emailAddress\n      customFields {\n        icaiRegistrationNumber\n        gstin\n      }\n    }\n    shippingAddress {\n      fullName\n      streetLine1\n      streetLine2\n      company\n      city\n      province\n      postalCode\n      countryCode\n      phoneNumber\n    }\n    shippingLines {\n      shippingMethod {\n        id\n        name\n      }\n      priceWithTax\n    }\n    lines {\n      id\n      unitPriceWithTax\n      linePriceWithTax\n      quantity\n      featuredAsset {\n        id\n        preview\n      }\n      productVariant {\n        id\n        name\n        price\n        product {\n          id\n          name\n          slug\n        }\n      }\n    }\n    payments {\n      id\n      state\n      method\n      amount\n      metadata\n      transactionId\n      customFields {\n        easebuzzToken\n      }\n    }\n    couponCodes\n    customFields {\n      attemptMonth\n      attemptYear\n      examLevel\n      additionalInformation\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query activeOrder {\n    activeOrder {\n      ...OrderDetail\n    }\n  }\n"): (typeof documents)["\n  query activeOrder {\n    activeOrder {\n      ...OrderDetail\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query orderByCode($code: String!) {\n    orderByCode(code: $code) {\n      ...OrderDetail\n    }\n  }\n"): (typeof documents)["\n  query orderByCode($code: String!) {\n    orderByCode(code: $code) {\n      ...OrderDetail\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query activeShippingMethods {\n    activeShippingMethods {\n      id\n      name\n      description\n      code\n    }\n  }\n"): (typeof documents)["\n  query activeShippingMethods {\n    activeShippingMethods {\n      id\n      name\n      description\n      code\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  fragment DetailedProduct on Product {\n    id\n    name\n    description\n    customFields {\n      language\n      additionalFeatures\n      ByFaculty\n    }\n    collections {\n      id\n      slug\n      name\n      breadcrumbs {\n        id\n        name\n        slug\n      }\n    }\n    facetValues {\n      facet {\n        id\n        code\n        name\n      }\n      id\n      code\n      name\n    }\n    featuredAsset {\n      id\n      preview\n    }\n    assets {\n      id\n      preview\n    }\n    optionGroups {\n      id\n      name\n      code\n      options {\n        id\n        name\n      }\n    }\n    variants {\n      id\n      name\n      priceWithTax\n      currencyCode\n      sku\n      stockLevel\n      options {\n        id\n        name\n        group {\n          id\n          name\n        }\n      }\n      featuredAsset {\n        id\n        preview\n      }\n    }\n  }\n"): (typeof documents)["\n  fragment DetailedProduct on Product {\n    id\n    name\n    description\n    customFields {\n      language\n      additionalFeatures\n      ByFaculty\n    }\n    collections {\n      id\n      slug\n      name\n      breadcrumbs {\n        id\n        name\n        slug\n      }\n    }\n    facetValues {\n      facet {\n        id\n        code\n        name\n      }\n      id\n      code\n      name\n    }\n    featuredAsset {\n      id\n      preview\n    }\n    assets {\n      id\n      preview\n    }\n    optionGroups {\n      id\n      name\n      code\n      options {\n        id\n        name\n      }\n    }\n    variants {\n      id\n      name\n      priceWithTax\n      currencyCode\n      sku\n      stockLevel\n      options {\n        id\n        name\n        group {\n          id\n          name\n        }\n      }\n      featuredAsset {\n        id\n        preview\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query product($slug: String, $id: ID) {\n    product(slug: $slug, id: $id) {\n      ...DetailedProduct\n    }\n  }\n"): (typeof documents)["\n  query product($slug: String, $id: ID) {\n    product(slug: $slug, id: $id) {\n      ...DetailedProduct\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  fragment ListedProduct on SearchResult {\n    productId\n    productName\n    slug\n    productAsset {\n      id\n      preview\n    }\n    currencyCode\n    priceWithTax {\n      ... on PriceRange {\n        min\n        max\n      }\n      ... on SinglePrice {\n        value\n      }\n    }\n  }\n"): (typeof documents)["\n  fragment ListedProduct on SearchResult {\n    productId\n    productName\n    slug\n    productAsset {\n      id\n      preview\n    }\n    currencyCode\n    priceWithTax {\n      ... on PriceRange {\n        min\n        max\n      }\n      ... on SinglePrice {\n        value\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query search($input: SearchInput!) {\n    search(input: $input) {\n      totalItems\n      items {\n        ...ListedProduct\n      }\n      facetValues {\n        count\n        facetValue {\n          id\n          name\n          facet {\n            id\n            name\n          }\n        }\n      }\n    }\n  }\n  \n"): (typeof documents)["\n  query search($input: SearchInput!) {\n    search(input: $input) {\n      totalItems\n      items {\n        ...ListedProduct\n      }\n      facetValues {\n        count\n        facetValue {\n          id\n          name\n          facet {\n            id\n            name\n          }\n        }\n      }\n    }\n  }\n  \n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query searchFacetValues($input: SearchInput!) {\n    search(input: $input) {\n      totalItems\n      facetValues {\n        count\n        facetValue {\n          id\n          name\n          facet {\n            id\n            name\n          }\n        }\n      }\n    }\n  }\n  \n"): (typeof documents)["\n  query searchFacetValues($input: SearchInput!) {\n    search(input: $input) {\n      totalItems\n      facetValues {\n        count\n        facetValue {\n          id\n          name\n          facet {\n            id\n            name\n          }\n        }\n      }\n    }\n  }\n  \n"];

export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;