apiVersion: v1
kind: ConfigMap
metadata:
  name: storefront-commerce-virtuals-config
  namespace: storefront-commerce-virtuals
data:
  NODE_ENV: "production"
  PORT: "8080"
  GRAPHQL_API_URL: "https://websiteadmin.appwallah.com/shop-api?vendure-token=shubham-agrawal-classes"
  VENDURE_API_URL: "https://websiteadmin.appwallah.com/shop-api?vendure-token=shubham-agrawal-classes"
  META_TITLE: "Commerce Virtuals"


