apiVersion: v1
kind: Secret
metadata:
  name: storefront-shubham-agrawal-classes-secrets
  namespace: storefront-shubham-agrawal-classes
type: Opaque
stringData:
  SESSION_SECRET: change-me
  STRIPE_PUBLISHABLE_KEY: ""
  EASEBUZZ_ENV: "sandbox"
  GOOGLE_CLIENT_ID: ""


